
sample_users = [
    {
        "id": 1,
        "twitter_id": '111',
        "twitter_name": 'Tester1',
        "full_name": 'Test Tester 1',
        "location": {'city': 'Ann Arbor', 'state': 'MI'}
    },
    {
        "id": 2,
        "twitter_id": '222',
        "twitter_name": 'Tester2',
        "full_name": 'Test Tester 2',
        "location": {'city': 'Ann Arbor', 'state': 'MI'}
    },
    {
        "id": 3,
        "twitter_id": '948889321',
        "twitter_name": 'JoelBentley7',
        "full_name": 'Joel Bentley',
        "location": {'city': 'Ann Arbor', 'state': 'MI'}
    }
]

sample_books = [{'book_id': 'QGhkQ',
                 'olid': 'OL16009269W',
                 'title': 'The Hunger Games',
                 'subtitle': '',
                 'author': 'Suzanne Collins',
                 'owner_id': 1,
                 'requested_by': [2],
                 'lentTo': None},
                {'book_id': 'bbd2j',
                 'olid': 'OL7318410M',
                 'title': 'KAFKA ON THE SHORE',
                 'subtitle': '',
                 'author': 'Haruki Murakami',
                 'owner_id': 1,
                 'requested_by': [],
                 'lentTo': None},
                {'book_id': 'QGhkr',
                 'olid': 'OL15936512W',
                 'title': 'Ready Player One',
                 'subtitle': '',
                 'author': 'Ernest Cline',
                 'owner_id': 2,
                 'requested_by': [1, 3],
                 'lentTo': None},
                {'book_id': 'bbd2K',
                 'olid': 'OL35628W',
                 'title': 'Dawn',
                 'subtitle': 'Book One of the Xenogenesis Series',
                 'author': 'Octavia E. Butler',
                 'owner_id': 2,
                 'requested_by': [],
                 'lentTo': None},
                {'book_id': '4n7Vz',
                 'olid': 'OL16159793M',
                 'title': 'The Name of the Wind',
                 'subtitle': '',
                 'author': 'Patrick Rothfuss',
                 'owner_id': 3,
                 'requested_by': [1, 2],
                 'lentTo': None},
                {'book_id': 'bad3K',
                 'olid': 'OL893527W',
                 'title': 'Dune',
                 'subtitle': '',
                 'author': 'Frank Herbert',
                 'owner_id': 3,
                 'requested_by': [1],
                 'lentTo': None}]
